---
- name: Setup static cluster configurations
  vars:
    relative_path: static-config
  block:
    - name: Clean static config manifests directory
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dest }}/{{ relative_path }}"
        state: absent
        owner: root
        group: root
        mode: '0755'

    - name: Create static config manifests directory
      ansible.builtin.file:
        path: "{{ k3s_server_manifests_dest }}/{{ relative_path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Deploy static manifests
      ansible.builtin.template:
        src: "{{ item | basename }}.yml.j2"
        dest: "{{ k3s_server_manifests_dest }}/{{ relative_path }}/{{ item | basename }}.yml"
        owner: root
        group: root
        mode: '0600'
      loop: "{{ k3s_cluster_static_manifests }}"
